apiVersion: v1
data:
  JWT_SECRET: cGFycXVlYWRlcm8tc2hhcmVkLWp3dC1zZWNyZXQtMjAyNi1taW4zMmJ5dGVz
  SUPABASE_DB_PASSWORD: ZGJzX2Rldl9Hb2QtMjAyNg==
kind: Secret
metadata:
  name: parqueadero-secrets
  namespace: parqueadero-buestan
---
apiVersion: v1
data:
  KONG_PG_PASSWORD: a29uZzEyMw==
kind: Secret
metadata:
  name: kong-db-secret
  namespace: parqueadero-buestan
