@base = http://localhost:3000
@id_person = b191a5b2-10cf-4246-a5f5-bd466cd4e231

### 1. Ver personas existentes
GET {{base}}/personas

### 2. Desactivar persona
PATCH {{base}}/personas/{{id_person}}
Content-Type: application/json

{
  "active": false
}

### 3. Ver personas (verificar que quedó inactiva)
GET {{base}}/personas

### 4. Activar persona
PATCH {{base}}/personas/{{id_person}}
Content-Type: application/json

{
  "active": true
}

### 5. Ver personas (verificar que quedó activa)
GET {{base}}/personas
