@base = http://localhost:3000
@id_person = f0909e0d-33a8-42b0-b841-092b2cba258b

# =============================================
# PASO 2 - PERSONA (datos personales)
# =============================================

### 2.1 Ver personas existentes
GET {{base}}/personas

### 2.2 Crear Persona
POST {{base}}/personas
Content-Type: application/json

{
  "dni": "1717481699",
  "email": "ptcd@test.com",
  "first_name": "Germans",
  "last_name": "Caceres",
  "middle_name": "PCc",
  "nationality": "Peru",
  "phone": "3001234567",
  "address": "Calle 123 # 45-67"
}

# =============================================
# ELIMINAR PERSONA
# =============================================

### 2.3 Ver persona por id
GET {{base}}/personas/{{id_person}}

### 2.4 Eliminar persona
DELETE {{base}}/personas/{{id_person}}

### 2.5 Ver personas (verificar eliminacion)
GET {{base}}/personas
